{
 "title": "ICON dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "ICON node metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ICON node total RAM Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "icon_total_ram {}", "legendFormat": "Total RAM" }
   ]
  },
  {
   "title": "ICON head block num",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "icon_head_block{}" }
   ]
  },
  {
   "title": "ICON node DB size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "icon_size_of_db {}", "legendFormat": "Size of DB Gb" }
   ]
  },
  {
   "title": "ICON node free space on disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Free space Gb" }
   ],
   "targets": [
    { "expr": "icon_free_space_of_disk {}", "legendFormat": "Free space on disk Gb" }
   ]
  },
  {
   "title": "ICON node RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "targets": [
    { "expr": "icon_mem_usage{}" }
   ]
  },
  {
   "title": "ICON average CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "icon_cpu_usage{}" }
   ]
  }
 ]
}